# Congestion Regime Thresholds
FREE_FLOW_DENSITY_RATIO = 0.2
STABLE_FLOW_DENSITY_RATIO = 0.6
UNSTABLE_FLOW_DENSITY_RATIO = 1.0

# Critical Values
STABILTY_THRESHOLD_SPEED_DROP = 30 # kmph
GRIDLOCK_VIOLATION_THRESHOLD = 0.4
